<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="LopendeBand" Id="{af1489a2-4b96-41ec-9023-dbc3371340a0}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK LopendeBand implements Motor
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[// kan aan en uit en reageert op errors, heeft lichtsensor aan het einde van het banddel]]></ST>
    </Implementation>
    <Method Name="HandleErrors" Id="{4482d789-05c3-4af2-9881-523428224908}">
      <Declaration><![CDATA[METHOD HandleErrors : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="LichtSensor" Id="{e295db0b-e309-4826-aa12-b8844bc13c3f}">
      <Declaration><![CDATA[METHOD LichtSensor : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Property Name="LopendeBandStatus" Id="{e25f0d20-e450-4241-b528-fbcd05cd4bf1}">
      <Declaration><![CDATA[PROPERTY LopendeBandStatus : ELopendeBandStatus]]></Declaration>
      <Get Name="Get" Id="{7bf1af54-c934-41f2-97ee-94bf6422b8bf}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[]]></ST>
        </Implementation>
      </Get>
      <Set Name="Set" Id="{89f06e9d-0dbc-4bb0-9d04-ba961ffc06be}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[]]></ST>
        </Implementation>
      </Set>
    </Property>
    <Method Name="MotorAan" Id="{9103c7af-6c47-4658-92d4-6ad86d23e3a9}">
      <Declaration><![CDATA[METHOD MotorAan
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="MotorUit" Id="{6cf8c88b-0239-4171-9cdc-4661629a3699}">
      <Declaration><![CDATA[METHOD MotorUit
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>