<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="LopendeBand" Id="{af1489a2-4b96-41ec-9023-dbc3371340a0}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK LopendeBand
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[// kan aan en uit en reageert op errors, heeft lichtsensor aan het einde van het banddel]]></ST>
    </Implementation>
    <Method Name="HandleErrors" Id="{4482d789-05c3-4af2-9881-523428224908}">
      <Declaration><![CDATA[METHOD HandleErrors : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="LichtSensor" Id="{e295db0b-e309-4826-aa12-b8844bc13c3f}">
      <Declaration><![CDATA[METHOD LichtSensor : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>