<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="fbTemploopband" Id="{fd55b582-6712-48f5-a30e-f1427c01e92c}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK fbTemploopband IMPLEMENTS temp_ITFloopband
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
	LoopbandActief : BOOL;
	
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="Beweeg" Id="{bfbb8d19-dde9-4864-ab11-58c8687d1a19}">
      <Declaration><![CDATA[{warning 'Add method implementation '}
METHOD Beweeg
]]></Declaration>
      <Implementation>
        <ST><![CDATA[LoopbandActief:= 1;
]]></ST>
      </Implementation>
    </Method>
    <Method Name="BeweegInLift" Id="{3e667e89-6b60-4a4e-8b87-7087f7f507b1}">
      <Declaration><![CDATA[{warning 'Add method implementation '}
METHOD BeweegInLift
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="Stop" Id="{67bd58cd-8dd1-4983-a51f-8b3ad74bddac}">
      <Declaration><![CDATA[{warning 'Add method implementation '}
METHOD Stop
]]></Declaration>
      <Implementation>
        <ST><![CDATA[LoopbandActief:= 0;]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>